### ISSUE TITLE
After running the crawler: Exception in Thread

### ISSUE THREAD

**Issue by kikeh** [yuhonglin/YTCrawl#3]
This is a **non-blocking issue**, since I get to receive all the youtube data. Also, I do not know what exactly causes it, because it happens a bit "randomly", meaning that, I tried with several Youtube Videos Ids and I only get this in some of them. This is the error I get:

```
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 1082, in run
  File "crawler.py", line 148, in update_cookie_and_sectiontoken
  File "crawler.py", line 168, in period_update
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'CookieJar'
```

**Comment by yuhonglin** [comment]
From the error report, it seems python complains that the variable "cookielib" is None. Can you successfully import "cookielib"?
